### ISSUE TITLE
Validate Promotion Tier - Define response body parameters

### ISSUE THREAD

**Issue by janiksam** [voucherifyio/voucherify-openapi#172]
## What

ReportedBy: @janiksam 

- Validate Promotions: **POST** `/promotions/tiers/{tier_id}/validation`

### Request

Define the following response parameters:
- [x] `tracking_id`
- [x] `discount_amount`
- [x] `applied_discount_amount`

**Comment by bandraszyk** [comment]
`tracking_id` - it's a hashed customer source_id identifier (Tomek can probably define it better)
`discount_amount` - when the order is given it should match the order's discount amount
`applied_discount_amount ` - when the order is given it should match the order's applied discount amount

**Comment by bandraszyk** [comment]
btw. this endpoint will be deprecated by end of this year (I hope)
