### ISSUE TITLE
Get Points Expiration - Define options for parameter

### ISSUE THREAD

**Issue by janiksam** [voucherifyio/voucherify-openapi#194]
## What

ReportedBy: @janiksam 

### Get Points Expiration

**GET** `/loyalties/{campaignId}/members/{memberId}/points-expiration`

### Request

Define the options available for `status`.
- one is definitely `ACTIVE`, what other ones are available?

**Comment by bandraszyk** [comment]
We have two possible values there: `ACTIVE` and `EXPIRED` but we do not list expired buckets

**Comment by janiksam** [comment]
in the response do this endpoint, I will only include the `ACTIVE` for status
