### ISSUE TITLE
Create Loyalty Campaign/Update Loyalty Campaign - Define how to create/update tier expiration mechanism

### ISSUE THREAD

**Issue by janiksam** [voucherifyio/voucherify-openapi#216]
## What

ReportedBy: @janiksam 

### Update Loyalty Campaign / Create Loyalty Campaign - defining the tier expiration configuration

**PUT** `/loyalties/{campaignId}`
**POST** `/loyalties`

#### Define how to create/update tier expiration mechanism

What are the options and what does each configuration mean?

```json
"loyalty_tiers_expiration": {
    "qualification_type": "BALANCE",
    "start_date": {
      "type": "IMMEDIATE"
    },
    "expiration_date": {
      "type": "CUSTOM",
      "extend": "P4M",
      "rounding": {
        "type": "CUSTOM",
        "strategy": "END",
        "unit": "MONTH",
        "value": 1
      }
    }
  }
```

so far it is defined as follows:

![Image](https://user-images.githubusercontent.com/95409292/204552462-d42e4a85-795f-44a7-8656-f9522ac1b5eb.png)

**Comment by lkulig** [comment]
Tier expiration payload is different depending on the qualifiation type

BALANCE

qualification_type -> BALANCE
start date -> type -> IMMEDIATE
expiration date -> type -> BALANCE_DROP / CUSTOM 
expiration date -> extend - ISO 8601
expiration date -> rounding -> type -> MONTH/ QUARTER/ HALF_YEAR/ YEAR
expiration date -> rounding -> type -> CUSTOM (custom rounding date)

CUSTOM ROUNDING (ONLY FOR BALANCE) - round to specific month
expiration date -> rounding -> unit -> MONTH,
expiration date -> rounding -> value: 0-11 (month number, 0 indexed, meaning january is 0)

POINTS_IN_PERIOD

qualification_type -> POINTS_IN_PERIOD (points collected in specific time period)
qualification_period -> MONTH/ QUARTER/ HALF_YEAR/ YEAR (qualification period)
start_date -> type -> immediate (after enough points are collected) / next_period (when next qualification period starts)

expiration_date -> type -> END_OF_PERIOD/ END_OF_NEXT_PERIOD (expire tiers at the end of current period or at the end of next period) ie. MONTH qualification period with END OF PERIOD expiration date means that tier will expire at the end of the month in which tier was assigned, whereas END_OF_NEXT_PERIOD means that tier will expire at the end of next month
expiration date -> extend - ISO 8601


hide expiration_date -> rounding -> strategy - not exposed for now in the API

**Comment by janiksam** [comment]
added the above to the openAPI definition
