### ISSUE TITLE
Examine Qualification - Define parameters

### ISSUE THREAD

**Issue by janiksam** [voucherifyio/voucherify-openapi#34]
## What

ReportedBy: @janiksam 

### Examine Qualification

**POST** `/vouchers/qualification`

### Request

- [x] Define or double check the following parameters:
    - [x] **Query**: `audienceRulesOnly` (double check), `order` (check available values)
    - [x] **Request**: `source_id` for customer/order
    - [x] **Response**: `tracking_id`

**Comment by bandraszyk** [comment]
- `audienceRulesOnly` it will check only the rules related to customer data like segments, customer redemption count. Rest will be omitted during validation. 
- `source_id` - external identified
- `tracking_id` - hashed customer source_id idetifier

**Comment by bandraszyk** [comment]
This endpoint I hope will be removed some day
