### ISSUE TITLE
[API Reference] Order Object

### ISSUE THREAD

**Issue by janiksam** [voucherifyio/voucherify-openapi#462]
**Describe the bug**
Order object missing `related_object`

**To Reproduce**
 https://docs.voucherify.io/reference/order-object

**Expected behavior**
Should show related_object

**Screenshots**
N/A

**Additional context**
N/A
---
### Standard Work
- [x] :one: Provide a title
- [x] :two: Provide a comment, following the template guidelines
- [x] :three: Add a label
    - `documentation` for Guides
    - `api` for API Reference (OpenAPI)
- [x] :four: Choose a milestone
    - If it's documentation related, then choose the Guides category (Getting Started, etc)
    - If it's API related, then choose the API Reference category (Introduction, Campaigns API, etc)
- [x] :five: Submit new issue

**Comment by p-woznikowski** [comment]
Fixed by Piotr Z. long time ago :)
