### ISSUE TITLE
[API Reference/Guides] Update the Checking eligibility page

### ISSUE THREAD

**Issue by kasjankotyniarsp** [voucherifyio/voucherify-openapi#475]
**Please note - I'm still working on this issue. I needed to drop it for a second.**

Please change the following data on the page https://docs.voucherify.io/docs/checking-eligibility

Case 1 not logged in request:

`{
    "scenario": "ALL",
    "mode": "BASIC",
    "order": {
        "items": [
            {
                "source_id": "bosch_product_1",
                "quantity": "1",
                "price": 10000,
                "related_object": "product",
                "product": {
                    "name": "BOSCH GDR 120-LI Cordless Impact Driver / Wrench"
                }
            },
            {
                "source_id": "digital_book",
                "quantity": "1",
                "price": 1500,
                "related_object": "product",
                "product": {
                    "name": "Digital Book"
                }
            }
        ]
    },
    "options": {
        "expand": [
            "redeemable"
        ]
    }
}`

Case 1 Response:
`{
    "redeemables": {
        "object": "list",
        "data_ref": "data",
        "data": [
            {
                "id": "promo_Fwbf1FWCQdqHIY3xlu6XDliB",
                "object": "promotion_tier",
                "created_at": "2023-09-26T09:48:44.948Z",
                "result": {
                    "discount": {
                        "type": "PERCENT",
                        "effect": "APPLY_TO_ORDER",
                        "percent_off": 10,
                        "is_dynamic": false
                    }
                },
                "order": {
                    "amount": 11500,
                    "discount_amount": 1150,
                    "total_discount_amount": 1150,
                    "total_amount": 10350,
                    "applied_discount_amount": 1150,
                    "total_applied_discount_amount": 1150,
                    "items": [
                        {
                            "object": "order_item",
                            "source_id": "bosch_product_1",
                            "related_object": "product",
                            "quantity": 1,
                            "amount": 10000,
                            "price": 10000,
                            "subtotal_amount": 10000,
                            "product": {
                                "name": "BOSCH GDR 120-LI Cordless Impact Driver / Wrench"
                            }
                        },
                        {
                            "object": "order_item",
                            "source_id": "digital_book",
                            "related_object": "product",
                            "quantity": 1,
                            "amount": 1500,
                            "price": 1500,
                            "subtotal_amount": 1500,
                            "product": {
                                "name": "Digital Book"
                            }
                        }
                    ],
                    "metadata": {},
                    "customer_id": null,
                    "referrer_id": null,
                    "object": "order"
                },
                "applicable_to": {
                    "data": [],
                    "total": 0,
                    "data_ref": "data",
                    "object": "list"
                },
                "inapplicable_to": {
                    "data": [],
                    "total": 0,
                    "data_ref": "data",
                    "object": "list"
                },
                "metadata": {},
                "name": "10% off for Everything",
                "campaign_id": "camp_nkcYmFDpw6fmzAOZQbqjXGzf",
                "campaign_name": "Promotions for everyone"
            }
        ],
        "total": 1,
        "has_more": false
    },
    "order": {
        "items": [
            {
                "object": "order_item",
                "source_id": "bosch_product_1",
                "related_object": "product",
                "quantity": 1,
                "price": 10000,
                "product": {
                    "name": "BOSCH GDR 120-LI Cordless Impact Driver / Wrench"
                }
            },
            {
                "object": "order_item",
                "source_id": "digital_book",
                "related_object": "product",
                "quantity": 1,
                "price": 1500,
                "product": {
                    "name": "Digital Book"
                }
            }
        ],
        "metadata": {},
        "customer_id": null,
        "referrer_id": null,
        "object": "order"
    },
    "stacking_rules": {
        "redeemables_limit": 30,
        "applicable_redeemables_limit": 5
    }
}`

Case 1 logged in request:
`{
    "scenario": "ALL",
    "mode": "BASIC",
    "order": {
        "items": [
            {
                "source_id": "bosch_product_1",
                "quantity": "1",
                "price": 10000,
                "related_object": "product",
                "product": {
                    "name": "BOSCH GDR 120-LI Cordless Impact Driver / Wrench"
                }
            },
            {
                "source_id": "digital_book",
                "quantity": "1",
                "price": 1500,
                "related_object": "product",
                "product": {
                    "name": "Digital Book"
                }
            }
        ]
    },
    "options": {
        "expand": [
            "redeemable"
        ]
    }
}`

Case 1 not logged in response:

**Comment by janiksam** [comment]
#477
