### ISSUE TITLE
[API Reference/order-object] 

### ISSUE THREAD

**Issue by p-woznikowski** [voucherifyio/voucherify-openapi#517]
## [Order object](https://docs.voucherify.io/reference/order-object)

Technical Account Managers: Asia Głowacka says that `source_id` requires a `related_object`.

Karolina Trzcionka thinks this info is worth being added to this doc.

Please edit the doc accordingly :)

**Comment by janiksam** [comment]
@p-woznikowski I'm looking for your guidance on what you think would be the most efficient place to underline this relationship. Below is a screenshot of where some information is stored for the Create Order endpoint and other endpoints which use this same object, ie. stackable redeem. What would you suggest would be a good way of showing this usage effectively?

<img width="924" alt="Screenshot 2023-10-31 at 13 46 47" src="https://github.com/voucherifyio/voucherify-openapi/assets/95409292/a577e4f1-e8b2-497b-96a3-bdd3f64d1748">

**Comment by p-woznikowski** [comment]
@janiksam, I'm so sorry, when I posted this issue, the bot assigned this to you automatically. 

I unassigned you immediately, so I thought you will get adequate notifications that you don't need to look into this 😕

This topic went to Piotr Zieliński, he said he'd take care of this. [Link to the Slack conversation](https://rspective.slack.com/archives/C03D95JG5DM/p1698392641180529).
