### ISSUE TITLE
List Promotion Tier from Campaign - Define response body has_more parameter

### ISSUE THREAD

**Issue by janiksam** [voucherifyio/voucherify-openapi#53]
## What

ReportedBy: @janiksam 

### List Promotion Tiers from Campaign

**GET** `/promotions/{campaignId}/tiers`

### Request

- Define response body parameter: `has_more`

**Comment by bandraszyk** [comment]
As query results are always limited (by limit parameter) then the `has_more` flag defines whether there are more records for given params and you are able to run another one (with a different page or different start date filter) to get more records

**Comment by janiksam** [comment]
updated definition per ^
