### ISSUE TITLE
[API Reference/Redeem] Stackable Discounts

### ISSUE THREAD

**Issue by janiksam** [voucherifyio/voucherify-openapi#530]
https://support.voucherify.io/article/23-whats-new-in-voucherify#v20220628

Table needs to be updated: The one in the description correctly says that a category is only displayed if the other 2 parameters are present. The one in the actual request body doesn't have this description and this information may be misleading because in order to get the category, you need `redeemable` and `redemption` (and of course `category`).

# Incorrect
<img width="891" alt="Screenshot 2023-11-02 at 23 01 58" src="https://github.com/voucherifyio/voucherify-openapi/assets/95409292/5d1f7847-8241-45c2-a3a5-007f9eac8853">

# Correct
<img width="537" alt="Screenshot 2023-11-02 at 23 02 09" src="https://github.com/voucherifyio/voucherify-openapi/assets/95409292/1b3bc71d-af4f-439e-b264-a5b0e1942483">

**Comment by p-zielinski** [comment]
Thanks
