### ISSUE TITLE
Customer object - Define parameters

### ISSUE THREAD

**Issue by janiksam** [voucherifyio/voucherify-openapi#78]
## What

ReportedBy: @janiksam 

### Request

Define parameters:
- [x] `phone`: A customer phone number. Is it mandatory when you try send out codes to customer via SMS channel?
- [x] `source_id`: A unique customer identifier. How to accurately describe the option of using the `tracking_id`?
- [x] `system_metadata.consents.date`: Define
- [x] `system_metadata.consents.value`: Define
- [x] `system_metadata.source`: Define

**Comment by janiksam** [comment]
still need to address the `source_id` / `tracking_id`

**Comment by bandraszyk** [comment]
`source_id` is an external identified, and tracking_id is just a hashed source_id (hashed for security reasons)
