### ISSUE TITLE
Update Order - Check whether all request body parameters are updateable

### ISSUE THREAD

**Issue by janiksam** [voucherifyio/voucherify-openapi#99]
## What

ReportedBy: @janiksam 

### Update Order

**PUT** `/orders/{orderId}`

#### Wholistic Endpoint Review

Check whether all request body parameters that are listed in the request body schema should be listed there, i.e. are they updateable?

**Comment by janiksam** [comment]
- status
- amount
- customer
- referrer
- initial_amount
- discount_amount
- items_discount_amount
- total_discount_amount
- total_amount
- items
- customer_id
- referrer_id
- metadata

**Comment by bandraszyk** [comment]
it's not recommended to update any of the discount amounts as they are calculated automatically during validation/redemption. Otherwise, we cannot tell how the system will calculate further discounts.
